update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,30 +1,56 @@
-
-name: CI
-
+#
+#name: CI
+#
+#on:
+#  pull_request:
+#    branches:
+#      - main
+#
+#jobs:
+#  build-and-test:
+#    runs-on: macos-latest
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#
+#      - name: Build and Test
+#        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
+#        with:
+#          project: MediStock.xcodeproj
+#          scheme: pack
+#          destination: 'platform=iOS Simulator,name=iPhone 15 Pro'
+#          action: test
+#          result-bundle-path: 'TestResults/TestResults.xcresult'
+#
+#      - name: Process Test Results
+#        uses: kishikawakatsumi/xcresulttool@v1
+#        with:
+#          path: TestResults/TestResults.xcresult
+#        if: success() || failure()
+name: iOS Build and Test
 on:
-  pull_request:
-    branches:
-      - main
-
+    pull_request:
+    branches: [ main ]
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  build-and-test:
-    runs-on: macos-latest
-
+    # This workflow contains a single job called "build-and-test"
+    build-and-test:
+    # The type of runner that the job will run on
+    runs-on: macos-14-xlarge
+    
+    timeout-minutes: 8
+    
+    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Build and Test
-        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
-        with:
-          project: MediStock.xcodeproj
-          scheme: pack
-          destination: 'platform=iOS Simulator,name=iPhone 15 Pro'
-          action: test
-          result-bundle-path: 'TestResults/TestResults.xcresult'
-
-      - name: Process Test Results
-        uses: kishikawakatsumi/xcresulttool@v1
-        with:
-          path: TestResults/TestResults.xcresult
-        if: success() || failure()
+    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+    - uses: actions/checkout@v4
+    
+    - name: Select Xcode
+        run: sudo xcode-select -switch /Applications/Xcode_15.4.app
+    
+    - name: Xcode version
+        run: /usr/bin/xcodebuild -version
+    
+    - name: Build and Test
+        run: xcodebuild clean build test -project MediStock.xcodeproj -scheme "pack" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.2" ONLY_ACTIVE_ARCH=YES
